---
- name: Create Ubuntu Cloud-Init Template on Proxmox VE (Defaults to Ubuntu 22.04 Cloud Image AMD64)
  hosts: "{{ host_group_var }}"
  become: true
  vars:
    host_group_var: "default"
    checksum_dest: "/var/lib/vz/template/cache/checksums/SHA256SUMS"
    checksum_url: "https://cloud-images.ubuntu.com/jammy/current/SHA256SUMS"
    checksum_gpg_dest: "/var/lib/vz/template/cache/checksums/SHA256SUMS.gpg"
    checksum_gpg_url: "https://cloud-images.ubuntu.com/jammy/current/SHA256SUMS.gpg"
    image_name: "jammy-server-cloudimg-amd64.img"
    image_dest: "/var/lib/vz/template/cache/{{ image_name }}"
    image_url: "https://cloud-images.ubuntu.com/jammy/current/{{ image_name }}"
    template_storage: "local-zfs"
    template_cloud_init_storage: "local-zfs"
    template_name: "ubuntu-22-04-cloud-init-template"
    public_key: ""
    template_id: 999
    overwrite_existing_template: false
  tasks:
    ####################################
    # Pre-Tasks: Handle VMID Conflicts #
    ####################################

    - name: Check if VMID {{ template_id }} already exists
      ansible.builtin.shell: |
        qm status {{ template_id }}
      register: vmid_check
      ignore_errors: true

    - name: Set fact if VMID exists
      ansible.builtin.set_fact:
        vm_exists: "{{ vmid_check.rc == 0 }}"

    - name: Fail if VMID is already in use and overwrite flag is false
      ansible.builtin.fail:
        msg: "VMID {{ template_id }} is already in use and overwrite_existing_template is set to false."
      when:
        - vm_exists
        - not overwrite_existing_template

    - name: Delete existing VM/template if VMID is already in use and overwrite flag is true
      ansible.builtin.command:
        cmd: qm destroy {{ template_id }} -purge -destroy-unreferenced-disks 1
      when:
        - vm_exists
        - overwrite_existing_template
      register: delete_existing_vm
      ignore_errors: true

    - name: Verify deletion of existing VM/template
      ansible.builtin.shell: |
        qm status {{ template_id }}
      register: vmid_post_delete
      when:
        - vm_exists
        - overwrite_existing_template
      ignore_errors: true

    - name: Fail if existing VM/template was not deleted
      ansible.builtin.fail:
        msg: "Failed to delete existing VM/template with VMID {{ template_id }}."
      when:
        - vm_exists
        - overwrite_existing_template
        - vmid_post_delete.rc == 0

    ##################################
    # Download and File Verification #
    ##################################

    - name: Create required directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: "0644"
      loop:
        - /var/lib/vz/template/cache/checksums

    - name: Download Ubuntu SHA256 checksums
      ansible.builtin.get_url:
        url: "{{ checksum_url }}"
        dest: "{{ checksum_dest }}"
        mode: "0644"
        validate_certs: true

    - name: Download Ubuntu SHA256 checksums GPG signature
      ansible.builtin.get_url:
        url: "{{ checksum_gpg_url }}"
        dest: "{{ checksum_gpg_dest }}"
        mode: "0644"
        validate_certs: true

    - name: Verify SHA256SUMS.gpg signature (initial attempt)
      ansible.builtin.command:
        cmd: gpg --verify SHA256SUMS.gpg SHA256SUMS
        chdir: "/var/lib/vz/template/cache/checksums"
      register: gpg_verify_initial
      ignore_errors: true

    - name: Extract missing GPG key IDs from verification output
      set_fact:
        missing_gpg_keys: "{{ gpg_verify_initial.stderr | regex_findall('using [A-Z]+ key ([A-Fa-f0-9]+)') | unique }}"

    - name: Debug missing GPG keys
      debug:
        msg: "Missing GPG Key IDs: {{ missing_gpg_keys }}"
      when: missing_gpg_keys | length > 0

    - name: Fail if GPG verification failed for reasons other than missing keys
      ansible.builtin.fail:
        msg: "GPG signature verification failed for SHA256SUMS.gpg. Error: {{ gpg_verify_initial.stderr }}"
      when:
        - gpg_verify_initial.rc != 0
        - missing_gpg_keys | length == 0

    - name: Import missing GPG keys from keyserver
      ansible.builtin.shell: |
        gpg --keyid-format long --keyserver hkp://keyserver.ubuntu.com --recv-keys 0x{{ item }}
      loop: "{{ missing_gpg_keys }}"
      when: missing_gpg_keys | length > 0
      register: gpg_import_results
      ignore_errors: true

    - name: Fail if any GPG key import failed
      ansible.builtin.fail:
        msg: "Failed to import one or more GPG keys: {{ gpg_import_results.results | json_query('[].stderr') }}"
      when: gpg_import_results.results | selectattr('rc', 'ne', 0) | list | length > 0

    - name: Re-verify SHA256SUMS.gpg signature after importing keys
      ansible.builtin.command:
        cmd: gpg --verify SHA256SUMS.gpg SHA256SUMS
        chdir: "/var/lib/vz/template/cache/checksums"
      register: gpg_verify_final
      ignore_errors: true

    - name: Fail if GPG signature verification failed after importing keys
      ansible.builtin.fail:
        msg: "GPG signature verification of SHA256SUMS.gpg failed after importing keys."
      when: gpg_verify_final.rc != 0

    - name: Extract the specific image SHA256 checksum
      ansible.builtin.shell: "grep {{ image_name }} {{ checksum_dest }} | awk '{print $1}'"
      register: extracted_checksum
      changed_when: false

    - name: Ensure checksum was extracted
      ansible.builtin.fail:
        msg: "Failed to extract SHA256 checksum for the Ubuntu image."
      when: extracted_checksum.stdout == ""

    - name: Download ubuntu 22.04 Cloud AMD64 Image with checksum verification
      ansible.builtin.get_url:
        url: "{{ image_url }}"
        dest: "{{ image_dest }}"
        checksum: "sha256:{{ extracted_checksum.stdout }}"
        mode: "0644"
        validate_certs: true

    - name: Ensure the image was downloaded and verified
      ansible.builtin.stat:
        path: "{{ image_dest }}"
      register: image_stat

    - name: Fail if image download failed verification
      ansible.builtin.fail:
        msg: "The Ubuntu image was not downloaded correctly or checksum verification failed."
      when: not image_stat.stat.exists

    ################
    # Modify Image #
    ################

    - name: Install libguestfs-tools
      ansible.builtin.apt:
        name: libguestfs-tools
        state: present
        update_cache: true

    - name: Install additional packages into the image
      ansible.builtin.command:
        cmd: virt-customize -a {{ image_dest }} --install qemu-guest-agent,net-tools
      register: virt_customize_result
      ignore_errors: false

    - name: Fail if virt-customize failed
      ansible.builtin.fail:
        msg: "Failed to install additional packages into the image. Error: {{ virt_customize_result.stderr }}"
      when: virt_customize_result.rc != 0

    ###############
    # VM Creation #
    ###############

    - name: Create Proxmox VM with Cloud-Init and Additional Packages
      block:
        - name: Create minimal VM using qm
          ansible.builtin.shell: |
            qm create {{ template_id }} \
            --name {{ template_name }} \
            --memory 2048 \
            --net0 virtio,bridge=vmbr0 \
            --scsihw virtio-scsi-pci \
            --ide2 {{ template_cloud_init_storage }}:cloudinit \
            --agent 1 \
            --ciuser ansible \
            --sshkey <(echo "{{ public_key }}") \
            --nameserver "192.168.25.100 192.168.25.101" \
            --ipconfig0 ip=dhcp
          args:
            executable: /bin/bash
          register: qm_create_result
          ignore_errors: false

        - name: Import image to Disk
          ansible.builtin.shell: |
            qm importdisk {{ template_id }} {{ image_dest }} {{ template_storage }}
          args:
            executable: /bin/bash
          register: qm_importdisk_result
          ignore_errors: false

        - name: Attach disk to VM and set boot order
          ansible.builtin.shell: |
            qm set {{ template_id }} --scsi0 {{ template_storage }}:vm-{{ template_id }}-disk-0 --boot c --bootdisk scsi0
          args:
            executable: /bin/bash
          register: qm_attach_image_result
          ignore_errors: false

        - name: Convert VM to template
          ansible.builtin.shell: |
            qm template {{ template_id }}
          args:
            executable: /bin/bash
          register: qm_template_result
          ignore_errors: false

        - name: Remove the image after template creation
          ansible.builtin.file:
            path: "{{ image_dest }}"
            state: absent
          when: qm_template_result.rc == 0

      rescue:
        - name: Cleanup - Delete VM if any step in the block fails
          ansible.builtin.command:
            cmd: qm destroy {{ template_id }} -purge -destroy-unreferenced-disks 1
          ignore_errors: true

        - name: Cleanup - Remove partially created image if exists
          ansible.builtin.file:
            path: "{{ image_dest }}"
            state: absent
          ignore_errors: true

        - name: Fail the playbook after cleanup
          ansible.builtin.fail:
            msg: "An error occurred during VM creation. Cleanup has been performed."
