awx_target_org: "Homelab"
awx_target_inv: "Homelab"
awx_git_credential: "Github - AWX SSH Key"
awx_project_branch: "main"
job_template_credentials:
  - Ansible Service Account - Homelab
  - Proxmox Primary
  - Proxmox NAS
