---
- name: Create AWX Resources For PVE CloudInit Templates
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Ensure required vars are present
      ansible.builtin.assert:
        that:
          - awx_target_org is defined
          - awx_target_inv is defined
          - awx_git_credential is defined
          - awx_project_branch is defined
          - job_template_credentials is defined
        fail_msg: "Required variables are missing. Please provide them using --extra-vars."

    - name: Verify that the AWX credentials are provided as environment variables
      ansible.builtin.fail:
        msg: AWX credentials are missing. Ensure CONTROLLER_HOST, CONTROLLER_USERNAME, and CONTROLLER_PASSWORD are set as environment variables.
      when: not (lookup('env', 'CONTROLLER_HOST') and lookup('env', 'CONTROLLER_USERNAME') and lookup('env', 'CONTROLLER_PASSWORD'))

    - name: Create primary pve host resource
      awx.awx.host:
        name: "proxmox-primary"
        description: Primary Proxmox Host
        inventory: "{{ awx_target_inv }}"
        state: present
        variables:
          hostname: "primary.pve.knighten.io"
          ansible_host: "primary.pve.knighten.io"

    - name: Create nas pve host resource
      awx.awx.host:
        name: "proxmox-nas"
        description: NAS Proxmox Host
        inventory: "{{ awx_target_inv }}"
        state: present
        variables:
          hostname: "nas.pve.knighten.io"
          ansible_host: "nas.pve.knighten.io"

    - name: Create proxmox host group
      awx.awx.group:
        name: "proxmox-hosts"
        description: "Proxmox Hosts"
        inventory: "{{ awx_target_inv }}"
        state: present
        hosts:
          - proxmox-primary
          - proxmox-nas

    - name: Create project
      awx.awx.project:
        name: Homelab - PVE CloudInit Templates
        state: present
        organization: "{{ awx_target_org }}"
        scm_type: git
        scm_url: git@github.com:Knighten-Homelab/ansible-proxmox-cloud-init-template-playbooks.git
        scm_branch: "{{ awx_project_branch }}"
        scm_update_on_launch: true
        scm_credential: "{{ awx_git_credential }}"

    - name: Create deploy job template for debian 12
      awx.awx.job_template:
        name: Debian 12 (Bookworm) Cloud-Init Template - Create
        job_type: run
        inventory: "{{ awx_target_inv }}"
        project: Homelab - PVE CloudInit Templates
        playbook: debian-12/create-pve-cloud-init-template.yaml
        become_enabled: true
        credentials: "{{ job_template_credentials }}"
        extra_vars:
          host_group_var: "proxmox-hosts"

    - name: Create deploy job template for ubuntu 22.04
      awx.awx.job_template:
        name: Ubuntu 22.04 (Jammy Jellyfish) Cloud-Init Template - Create
        job_type: run
        inventory: "{{ awx_target_inv }}"
        project: Homelab - PVE CloudInit Templates
        playbook: ubuntu-22-04/create-pve-cloud-init-template.yaml
        become_enabled: true
        credentials: "{{ job_template_credentials }}"
        extra_vars:
          host_group_var: "proxmox-hosts"
