---
- name: Create Debian Cloud-Init Template on Proxmox VE
  hosts: "{{ host_group_var }}"
  become: true
  vars:
    checksum_dest: "/var/lib/vz/template/cache/checksums/SHA512SUMS"
    public_key: ""
  tasks:
    ##################################
    # Download and File Verification #
    ##################################

    - name: Create required directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0644'
      loop:
        - /var/lib/vz/template/cache/checksums

    - name: Download Debian SHA512 checksums
      ansible.builtin.get_url:
        url: https://cdimage.debian.org/images/cloud/bookworm/latest/SHA512SUMS
        dest: "{{ checksum_dest }}"
        mode: '0644'

    - name: Extract the specific image SHA512 checksum
      ansible.builtin.shell: "grep debian-12-generic-amd64.qcow2 {{ checksum_dest }} | awk '{print $1}'"
      register: extracted_checksum
      changed_when: false

    - name: Ensure checksum was extracted
      ansible.builtin.fail:
        msg: "Failed to extract SHA512 checksum for the Debian image."
      when: extracted_checksum.stdout == ""

    - name: Download Debian Generic Cloud AMD64 Image with checksum verification
      ansible.builtin.get_url:
        url: https://cdimage.debian.org/images/cloud/bookworm/latest/debian-12-generic-amd64.qcow2
        dest: /var/lib/vz/template/cache/debian-12-generic-amd64.qcow2
        checksum: "sha512:{{ extracted_checksum.stdout }}"
        mode: '0644'
        validate_certs: yes

    - name: Ensure the image was downloaded and verified
      ansible.builtin.stat:
        path: /var/lib/vz/template/cache/debian-12-generic-amd64.qcow2
      register: image_stat

    - name: Fail if image download failed verification
      ansible.builtin.fail:
        msg: "The Debian image was not downloaded correctly or checksum verification failed."
      when: not image_stat.stat.exists

    ###############
    # VM Creation #
    ###############

    - name: Create minimal VM using qm
      ansible.builtin.shell: |
        qm create 150 \
        --name debian-12-cloud-init-template \
        --memory 2048 \
        --net0 virtio,bridge=vmbr0 \
        --scsihw virtio-scsi-pci \
        --ide2 local-zfs:cloudinit \
        --ciuser ansible \
        --sshkey <(echo "{{ public_key }}") \
        --nameserver "192.168.25.100 192.168.25.101" \
        --ipconfig0 ip=dhcp
      args:
        executable: /bin/bash
      
    - name: Import qcoqw2 image to Disk
      ansible.builtin.shell: |
        qm importdisk 150 /var/lib/vz/template/cache/debian-12-generic-amd64.qcow2 local-zfs
      args:
        executable: /bin/bash

    - name: Attach disk to VM and set boot order
      ansible.builtin.shell: |
        qm set 150 --scsi0 local-zfs:vm-150-disk-0 --boot c --bootdisk scsi0
      args:
        executable: /bin/bash

    - name: Convert VM to template
      ansible.builtin.shell: |
        qm template 150
      args:
        executable: /bin/bash