#!/usr/bin/env bash

DIR="debian-12"

# Check for staged changes in the specific directory
if git diff --cached --name-only | grep --quiet "^$DIR/"
then
  echo -e "\nChanges in $DIR detected..."

  echo -e "\nansible-lint in $DIR..."
  (cd $DIR && ansible-lint)
  

else
  echo "No changes in $DIR, skipping Go Pre Commit Script."
fi

